// this file is generated by grandet, please don't edit it directly!
// see https://github.com/setekhid/grandet

package assets

import (
	gr "github.com/setekhid/grandet"
)

// Grandet represents the package assets
var Grandet gr.Assets

type grandetsAssets struct {
	gr.AssetsImpl
}

func (ga *grandetsAssets) registAssets() {

	ga.Init("github.com/setekhid/grandet/assets")

	// call asset registers

	ga.registAssetbe15b803eeedfca1b05349e44ac31fb5()

	ga.registAssetd3929716b325e1b72abc88a359aae41f()

	Grandet = ga
}
