// this file is generated by grandet, please don't edit it directly!
// see https://github.com/setekhid/grandet

package assets

import (
	gr "github.com/setekhid/grandet"
)

// Grandet represents the package assets
var Grandet gr.Grandet

type grandetsAssets struct {
	gr.GrandetAssets
}

func (ga *grandetsAssets) registAssets() {

	ga.GrandetAssets.Init("github.com/setekhid/grandet/assets")

	// call asset registers

	ga.registAsset527e6588aa0d3145c61ebe30c995dbe3()

	ga.registAsset8331f6c186d39cfffbaad6a303cd4b2a()

	Grandet = ga
}
