// this file is generated by grandet, please don't edit it directly!
// see https://github.com/setekhid/grandet

package assets

import (
	gr "github.com/setekhid/grandet"
)

// Grandet represents the package assets
var Grandet gr.Grandet

type grandetsAssets struct {
	gr.GrandetAssets
}

func (ga *grandetsAssets) registAssets() {

	ga.GrandetAssets.Init()

	// call asset registers

	ga.registAsset0()

	ga.registAsset1()

	Grandet = ga
}
